In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [3]:
np.__version__

'1.18.1'

In [4]:
import array

l = list(range(10))
s = array.array('i', l);s

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating an array

In [5]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [6]:
np.array([3.14, 4, 3, 2])

array([3.14, 4.  , 3.  , 2.  ])

In [7]:
# explicitly setting the datatype
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [8]:
# multidimensional array
np.array([range(i, i+3) for i in [2, 4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating array from scratch

In [9]:
# creating array of length 10 zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# creating 3x5 array of value 1
np.ones([3,5], dtype=np.int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
#creating a 3x5 array of value 3.14
np.full([3, 5], 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
# creating array of range 0 to 20 of even numbers
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# creating array of evenly spaced values from 0-1
np.linspace(0, 1, 5, dtype=float)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
# array of random values from 0 - 1, evenly distributed
np.random.random([3,3])

array([[0.73320085, 0.97149109, 0.23556568],
       [0.08755195, 0.05836431, 0.07876844],
       [0.68493746, 0.39952158, 0.79840332]])

In [15]:
# array of normally distributed random values of any given mean and variance
np.random.normal(0, 1, [3,3])

array([[ 0.33403064, -2.98054658,  1.29534356],
       [-0.20243857,  1.12904845,  1.53861297],
       [-0.78600682, -0.62869645,  0.63420005]])

In [16]:
np.random.randint(0, 10, [3,3])

array([[6, 3, 1],
       [1, 5, 8],
       [1, 2, 7]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.empty(3)

array([1., 1., 1.])

In [19]:
np.linspace(0, 3, 5)

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

###  numpy attributes

In [20]:
np.random.seed(7)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=[3,5])
x3 = np.random.randint(10, size=[3, 4, 5])
# print(x1)
# print(x2)
print(x3)

[[[5 8 8 7 5]
  [0 0 2 8 9]
  [6 4 9 7 3]
  [3 8 3 0 1]]

 [[0 0 6 7 7]
  [9 3 0 7 7]
  [7 0 5 4 3]
  [1 3 1 3 4]]

 [[3 1 9 5 9]
  [1 2 3 2 2]
  [5 7 3 0 9]
  [9 3 4 5 3]]]


In [21]:
x2.ndim

2

In [22]:
x1.shape

(6,)

In [23]:
x3.size

60

### Array indexing 

In [24]:
x1

array([4, 9, 6, 3, 3, 7])

In [25]:
# prints the first index value of the array
x1[0]

4

In [26]:
x1[4]

3

In [27]:
# indexing from the end of an array
x1[-1], x1[-2]

(7, 3)

In [28]:
# indexin gmultidimensional arrays
x2

array([[7, 9, 7, 8, 9],
       [8, 7, 6, 4, 0],
       [7, 0, 7, 6, 3]])

In [29]:
#first value of the first array
x2[0, 0]

7

In [30]:
#third array first value
x2[2, 0]

7

In [31]:
x2[2, -1]

3

In [32]:
x2[0,0]= 12
x2

array([[12,  9,  7,  8,  9],
       [ 8,  7,  6,  4,  0],
       [ 7,  0,  7,  6,  3]])

In [33]:
x1.astype(np.int)
x1

array([4, 9, 6, 3, 3, 7])

###  Array Slicing: Accessing Subarray

An array subset can be created using this method, **`x[start:stop:steps]`**

In [34]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# first 5 elements of the array
x[:5]

array([0, 1, 2, 3, 4])

In [36]:
# elements after the 5th index
x[5:]

array([5, 6, 7, 8, 9])

In [37]:
# elements from the 4th index to the (nth - 1) index
x[4:7]

array([4, 5, 6])

In [38]:
# from the first index to the last index, moving 2 steps 
x[1::2]

array([1, 3, 5, 7, 9])

In [39]:
# all index in reversed order
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [40]:
x[5::-2]

array([5, 3, 1])

In [41]:
# multidimensional slicing 
x2[:2, :3]

array([[12,  9,  7],
       [ 8,  7,  6]])

### Concatenation and Splitting
Single array values of any dimensions can be joined together to form a new array

This can be done through. **`np.concatenate`**, **`np.vstack`**, **`np.hstack`**

In [42]:
# concatenating
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [43]:
# multiple 1-d arrays
z = np.array([9, 8, 7, 6])
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 9, 8, 7, 6])

In [44]:
# concatenating multi dimensional arrays
a = np.array([[1, 2, 3],
              [5, 6, 7]
             ])

np.concatenate([a,a])

array([[1, 2, 3],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [45]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [5, 6, 7, 5, 6, 7]])

In [46]:
# vstack, vertical stacking
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4],
                ])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [47]:
# hstack, horizontal stacking
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting

In [48]:
# splitting an array into specified indices
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
x1, x2, x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [49]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
# vsplit : vertical splitting
upper, lower = np.vsplit(grid, 2)
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [51]:
# hsplit : column-wise splitting
feature, labels = np.hsplit(grid, [3,])
feature, labels

(array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]))

### Numpy computation(universal function)

In [52]:
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [53]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

4.56 s ± 51.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [54]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
np.add(x, x)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [56]:
np.subtract(x, 2)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17, 18, 19, 20, 21])

In [57]:
np.divide(x, 3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ,
       3.33333333, 3.66666667, 4.        , 4.33333333, 4.66666667,
       5.        , 5.33333333, 5.66666667, 6.        , 6.33333333,
       6.66666667, 7.        , 7.33333333, 7.66666667])

In [58]:
np.power(x, 2)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [62]:
np.mod(x, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2])

In [63]:
x =  np.array([-1, -2, -5, -9,])
np.abs(x)

array([1, 2, 5, 9])

#### Trigonometrics

In [65]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [66]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [67]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [68]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [70]:
x = [-1, 0, 1]

In [71]:
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [72]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [73]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

####  log and exponents

In [74]:
x = [1, 2, 3]
x

[1, 2, 3]

In [75]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [76]:
np.exp2(x)

array([2., 4., 8.])

In [77]:
np.power(x, 4)

array([ 1, 16, 81])

In [78]:
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [79]:
np.log2(x)

array([0.       , 1.       , 1.5849625])

In [80]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125])

In [82]:
# Special ufuncs operations(scipy.special)
from scipy import special
x = [1, 5, 10]
x

[1, 5, 10]

In [83]:
# gamma
special.gamma(x)

array([1.0000e+00, 2.4000e+01, 3.6288e+05])

In [84]:
special.gammaln(x)

array([ 0.        ,  3.17805383, 12.80182748])

In [86]:
special.beta(x,2)

array([0.5       , 0.03333333, 0.00909091])

In [87]:
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

In [97]:
np.sum(x)

15

In [98]:
np.cumsum(x)

array([ 1,  3,  6, 10, 15])

In [99]:
np.prod(x)

120

In [101]:
np.cumprod(x)

array([  1,   2,   6,  24, 120])

In [102]:
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

### Aggregations

In [106]:
big_data = np.random.rand(100000)
big_data

array([0.31063457, 0.52798682, 0.04436271, ..., 0.15059736, 0.90641924,
       0.67323425])

In [107]:
np.sum(big_data)

50041.02987982194

In [108]:
np.min(big_data)

1.172694131090779e-05

In [109]:
np.max(big_data)

0.9999997207656334

In [120]:
np.random.seed(7)
m = np.random.random((3, 4))
m

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904]])

In [122]:
m.min()

0.07205113335976154

In [123]:
m.max()

0.9779895119966027

In [124]:
m.sum()

6.3590489834653905

In [125]:
m.min(axis=0)

array([0.07630829, 0.4998825 , 0.43840923, 0.07205113])

In [126]:
m.max(axis=1)

array([0.77991879, 0.97798951, 0.80373904])

In [129]:
m.sum(axis=1)

array([2.01810149, 2.08965698, 2.25129051])

In [131]:
m.mean()

0.5299207486221159

In [133]:
m.mean(axis=0)

array([0.44091226, 0.60609905, 0.53958656, 0.53308512])

In [134]:
m.std(axis=1)

array([0.27906871, 0.32058065, 0.20137936])

In [139]:
m.argmax()

4

In [150]:
# percentile
for x in [0, 25, 50, 75, 100]:
    print(x,'%', '  : ', np.percentile(m, x))

0 %   :  0.07205113335976154
25 %   :  0.3959166686061379
50 %   :  0.5198081670351857
75 %   :  0.7375785814332346
100 %   :  0.9779895119966027


In [152]:
np.all(m)

True