In [6]:
%reload_ext autoreload
%autoreload 2

In [7]:
import numpy as np

In [8]:
np.__version__

'1.18.1'

In [9]:
import array

l = list(range(10))
s = array.array('i', l);s

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating an array

In [10]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [11]:
np.array([3.14, 4, 3, 2])

array([3.14, 4.  , 3.  , 2.  ])

In [12]:
# explicitly setting the datatype
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [13]:
# multidimensional array
np.array([range(i, i+3) for i in [2, 4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating array from scratch

In [14]:
# creating array of length 10 zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# creating 3x5 array of value 1
np.ones([3,5], dtype=np.int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
#creating a 3x5 array of value 3.14
np.full([3, 5], 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
# creating array of range 0 to 20 of even numbers
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
# creating array of evenly spaced values from 0-1
np.linspace(0, 1, 5, dtype=float)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# array of random values from 0 - 1, evenly distributed
np.random.random([3,3])

array([[0.65145273, 0.77829224, 0.90236147],
       [0.73697651, 0.99589278, 0.52245441],
       [0.65242133, 0.56515878, 0.2756308 ]])

In [20]:
# array of normally distributed random values of any given mean and variance
np.random.normal(0, 1, [3,3])

array([[ 1.85779077, -0.61596325,  0.13842354],
       [ 0.34509992, -2.00734815, -0.31637939],
       [-0.57000568, -1.82256652,  0.3769996 ]])

In [21]:
np.random.randint(0, 10, [3,3])

array([[9, 1, 1],
       [0, 8, 1],
       [7, 9, 7]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.empty(3)

array([1., 1., 1.])

In [24]:
np.linspace(0, 3, 5)

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

###  numpy attributes

In [25]:
np.random.seed(7)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=[3,5])
x3 = np.random.randint(10, size=[3, 4, 5])
# print(x1)
# print(x2)
print(x3)

[[[5 8 8 7 5]
  [0 0 2 8 9]
  [6 4 9 7 3]
  [3 8 3 0 1]]

 [[0 0 6 7 7]
  [9 3 0 7 7]
  [7 0 5 4 3]
  [1 3 1 3 4]]

 [[3 1 9 5 9]
  [1 2 3 2 2]
  [5 7 3 0 9]
  [9 3 4 5 3]]]


In [34]:
x2.ndim

2

In [35]:
x1.shape

(6,)

In [36]:
x3.size

60

### Array indexing 

In [37]:
x1

array([4, 9, 6, 3, 3, 7])

In [39]:
# prints the first index value of the array
x1[0]

4

In [40]:
x1[4]

3

In [46]:
# indexing from the end of an array
x1[-1], x1[-2]

(7, 3)

In [47]:
# indexin gmultidimensional arrays
x2

array([[7, 9, 7, 8, 9],
       [8, 7, 6, 4, 0],
       [7, 0, 7, 6, 3]])

In [59]:
#first value of the first array
x2[0, 0]

7

In [61]:
#third array first value
x2[2, 0]

7

In [62]:
x2[2, -1]

3

In [63]:
x2[0,0]= 12
x2

array([[12,  9,  7,  8,  9],
       [ 8,  7,  6,  4,  0],
       [ 7,  0,  7,  6,  3]])

In [75]:
x1.astype(np.int)
x1

array([3, 9, 6, 3, 3, 7])

###  Array Slicing: Accessing Subarray

An array subset can be created using this method, **`x[start:stop:steps]`**

In [77]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# first 5 elements of the array
x[:5]

array([0, 1, 2, 3, 4])

In [81]:
# elements after the 5th index
x[5:]

array([5, 6, 7, 8, 9])

In [82]:
# elements from the 4th index to the (nth - 1) index
x[4:7]

array([4, 5, 6])

In [84]:
# from the first index to the last index, moving 2 steps 
x[1::2]

array([1, 3, 5, 7, 9])

In [87]:
# all index in reversed order
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [88]:
x[5::-2]

array([5, 3, 1])

In [90]:
# multidimensional slicing 
x2[:2, :3]

array([[12,  9,  7],
       [ 8,  7,  6]])

### Concatenation and Splitting
Single array values of any dimensions can be joined together to form a new array

This can be done through. **`np.concatenate`**, **`np.vstack`**, **`np.hstack`**

In [95]:
# concatenating
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [97]:
# multiple 1-d arrays
z = np.array([9, 8, 7, 6])
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 9, 8, 7, 6])

In [111]:
# concatenating multi dimensional arrays
a = np.array([[1, 2, 3],
              [5, 6, 7]
             ])

np.concatenate([a,a])

array([[1, 2, 3],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [116]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [5, 6, 7, 5, 6, 7]])

In [124]:
# vstack, vertical stacking
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4],
                ])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [127]:
# hstack, horizontal stacking
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[  9,   8,   7,  99, 100],
       [  6,   5,   4,  99, 100]])

### Splitting

In [161]:
# splitting an array into specified indices
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
x1, x2, x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [216]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [190]:
# vsplit : vertical splitting
upper, lower = np.vsplit(grid, 2)
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [207]:
# hsplit : column-wise splitting
feature, labels = np.hsplit(grid, [3,])
feature, labels

(array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]))

### Numpy computation(universal function)