In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

sns.set()

## Pandas Series
This is a one-dimensional array of indexed data, that can be created from a list or array

In [3]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
# the value of the pd.Series
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [5]:
# the pd.Series index
data.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
# getting the value of a pd.Series through it's index
data[1]

0.5

In [7]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [8]:
# pd.Series object have index that are explicitly defined
data = pd.Series([.25, .50, .75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [9]:
data['b']

0.5

In [10]:
data = pd.Series([.25, .50, .75, 1.0], index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [11]:
data[3]

0.75

In [12]:
# a pd.Series object can be made from a python dict
population_dict = {'california':38.33,
                   'texas':26.44,
                   'new york' : 19.65,
                   'florida':19.55,
                   'illinois':12.88,
                  }
population = pd.Series(population_dict)
population

california    38.33
texas         26.44
new york      19.65
florida       19.55
illinois      12.88
dtype: float64

In [13]:
population['california']

38.33

In [14]:
population['california':'illinois']

california    38.33
texas         26.44
new york      19.65
florida       19.55
illinois      12.88
dtype: float64

In [15]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [16]:
# pd.Series object from a scalar value
pd.Series(5, index=range(100, 400, 100))

100    5
200    5
300    5
dtype: int64

In [17]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [18]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

# Pandas DataFrame

In [19]:
area_dict = {
    'california':42.39,
    'texas':69.56,
    'new york':14.12,
    'florida':17.02,
    'illinois':14.99
}
area = pd.Series(area_dict)
area

california    42.39
texas         69.56
new york      14.12
florida       17.02
illinois      14.99
dtype: float64

In [20]:
states = pd.DataFrame({'population':population,
                      'area':area,})
states

population   area
california       38.33  42.39
texas            26.44  69.56
new york         19.65  14.12
florida          19.55  17.02
illinois         12.88  14.99

In [21]:
states.index

Index(['california', 'texas', 'new york', 'florida', 'illinois'], dtype='object')

In [22]:
states.values

array([[38.33, 42.39],
       [26.44, 69.56],
       [19.65, 14.12],
       [19.55, 17.02],
       [12.88, 14.99]])

In [23]:
states['area']

california    42.39
texas         69.56
new york      14.12
florida       17.02
illinois      14.99
Name: area, dtype: float64

In [24]:
states['population']

california    38.33
texas         26.44
new york      19.65
florida       19.55
illinois      12.88
Name: population, dtype: float64

In [25]:
pd.DataFrame(population, columns=['population'])

population
california       38.33
texas            26.44
new york         19.65
florida          19.55
illinois         12.88

In [26]:
pd.DataFrame([{'a':1, 'b':2}, {'b':3, 'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [27]:
pd.DataFrame({'population':population, 'area':area})

population   area
california       38.33  42.39
texas            26.44  69.56
new york         19.65  14.12
florida          19.55  17.02
illinois         12.88  14.99

In [28]:
pd.DataFrame(np.random.rand(3,2), columns=['foo', 'bar'], index=['a', 'b', 'c'])

foo       bar
a  0.247918  0.594358
b  0.281593  0.290201
c  0.723175  0.953166

In [29]:
area = pd.Series({
    'california':42.39,
    'new york':14.17,
    'florida':17.03,
    'illinois':14.99
})

pop = pd.Series({
    'california':38.39,
    'new york':19.65,
    'illinois':14.99,
    'florida':19.63,
    
})

data = pd.DataFrame({'area':area, 'pop':pop})
data

area    pop
california  42.39  38.39
florida     17.03  19.63
illinois    14.99  14.99
new york    14.17  19.65

In [30]:
data['area']

california    42.39
florida       17.03
illinois      14.99
new york      14.17
Name: area, dtype: float64

In [31]:
data['pop']

california    38.39
florida       19.63
illinois      14.99
new york      19.65
Name: pop, dtype: float64

In [32]:
data.area is data['area']

True

In [33]:
# creating a new column from existing ones
data['density'] = data['pop'] / data['area']
data

area    pop   density
california  42.39  38.39  0.905638
florida     17.03  19.63  1.152672
illinois    14.99  14.99  1.000000
new york    14.17  19.65  1.386733

In [34]:
data.values

array([[42.39      , 38.39      ,  0.90563812],
       [17.03      , 19.63      ,  1.15267176],
       [14.99      , 14.99      ,  1.        ],
       [14.17      , 19.65      ,  1.38673253]])

In [35]:
data.T

california    florida  illinois   new york
area      42.390000  17.030000     14.99  14.170000
pop       38.390000  19.630000     14.99  19.650000
density    0.905638   1.152672      1.00   1.386733

In [36]:
data.values[0]

array([42.39      , 38.39      ,  0.90563812])

In [37]:
data['area']

california    42.39
florida       17.03
illinois      14.99
new york      14.17
Name: area, dtype: float64

In [38]:
data

area    pop   density
california  42.39  38.39  0.905638
florida     17.03  19.63  1.152672
illinois    14.99  14.99  1.000000
new york    14.17  19.65  1.386733

In [39]:
data.iloc[:3, :2]


area    pop
california  42.39  38.39
florida     17.03  19.63
illinois    14.99  14.99

In [40]:
data.loc[:'illinois', :'pop']

area    pop
california  42.39  38.39
florida     17.03  19.63
illinois    14.99  14.99

In [41]:
data.loc[data['density'] > 1.0, ['pop', 'density']]

pop   density
florida   19.63  1.152672
new york  19.65  1.386733

In [42]:
data

area    pop   density
california  42.39  38.39  0.905638
florida     17.03  19.63  1.152672
illinois    14.99  14.99  1.000000
new york    14.17  19.65  1.386733

In [43]:
data.iloc[0, 2] = 9.0
data

area    pop   density
california  42.39  38.39  9.000000
florida     17.03  19.63  1.152672
illinois    14.99  14.99  1.000000
new york    14.17  19.65  1.386733

In [44]:
data.iloc[1, :2]

area    17.03
pop     19.63
Name: florida, dtype: float64

In [45]:
data.loc['florida':, :]

area    pop   density
florida   17.03  19.63  1.152672
illinois  14.99  14.99  1.000000
new york  14.17  19.65  1.386733

In [46]:
data[data.density > 1]

area    pop   density
california  42.39  38.39  9.000000
florida     17.03  19.63  1.152672
new york    14.17  19.65  1.386733

## Operating on data in pandas

In [47]:
np.random.seed(42)
rng = np.random.RandomState(42)
ser = pd.Series(np.random.randint(0, 10,4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [48]:
df = pd.DataFrame(rng.randint(0, 10, (3,4)), columns=['a', 'b', 'c', 'd'])
df

a  b  c  d
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7

In [49]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [50]:
np.sin(df * np.pi / 4)

a             b         c             d
0 -1.000000  7.071068e-01 -0.707107  1.224647e-16
1 -1.000000  7.071068e-01  1.000000 -1.000000e+00
2 -0.707107  1.224647e-16  0.707107 -7.071068e-01

In [51]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')

population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [52]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [53]:
pd.DataFrame({'area':area, 'population':population}).isnull()

area  population
Alaska      False        True
California  False       False
New York     True       False
Texas       False       False

### Handling missing data

In [54]:
1 + np.nan

nan

In [55]:
0 * np.nan

nan

In [56]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [57]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [58]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [59]:
x[0] = np.nan
x

0    NaN
1    1.0
dtype: float64

In [60]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [61]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [62]:
# droping missing values 
data.dropna()

0        1
2    hello
dtype: object

In [63]:
df = pd.DataFrame([
    [1, np.nan, 2],
    [2, 3, 5],
    [np.nan, 4, 6],
], columns=['A', 'B', 'C'])
df

A    B  C
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [64]:
# dropping an entire row
df.dropna()

A    B  C
1  2.0  3.0  5

In [65]:
df.dropna(axis='columns')

C
0  2
1  5
2  6

In [66]:
df['D'] = np.nan
df

A    B  C   D
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [67]:
df.dropna(axis=0, how='all', thresh=3)

A    B  C   D
1  2.0  3.0  5 NaN

In [68]:
# fillna()
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [69]:
# fill-in the missing values with 0
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [70]:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [71]:
df

A    B  C   D
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [72]:
df.fillna(method='ffill', axis=1)

A    B    C    D
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

### Aggregation and grouping

In [76]:
# working with the planet dataset
planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [79]:
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [80]:
rng = np.random.RandomState(42)
df = pd.DataFrame({'A':rng.rand(5), 
                  'B':rng.rand(5)})
df

A         B
0  0.374540  0.155995
1  0.950714  0.058084
2  0.731994  0.866176
3  0.598658  0.601115
4  0.156019  0.708073

In [84]:
# mean coulmn wise
df.mean()

A    0.562385
B    0.477888
dtype: float64

In [85]:
# mean across the rows
df.mean(axis=1)

0    0.265267
1    0.504399
2    0.799085
3    0.599887
4    0.432046
dtype: float64

In [92]:
planets.dropna().describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [100]:
planets.count()

method            1035
number            1035
orbital_period     992
mass               513
distance           808
year              1035
dtype: int64

### split-apply-combine

In [106]:
df = pd.DataFrame({
    'key':list('ABC'*2),
    'data' :range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [116]:
# my implementation of the groupby method
# splitting
by_a = df[df['key'] == 'A']
by_b = df[df['key'] == 'B']
by_c = df[df['key'] == 'C']

# apply
by_a_mean = by_a.sum()
by_b_mean = by_b.sum()
by_c_mean = by_c.sum()

# combine
abc_combined = np.stack([by_a_mean, by_b_mean, by_c_mean])
abc_combined

In [140]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [142]:
planets.head()


method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [145]:
# groupping the planet's dataset by its method and orbital_period
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [148]:
for (method, group) in planets.groupby('method'):
    print(f'{method:.30s} shape={(group.shape)}')

Astrometry shape=(2, 6)
Eclipse Timing Variations shape=(9, 6)
Imaging shape=(38, 6)
Microlensing shape=(23, 6)
Orbital Brightness Modulation shape=(3, 6)
Pulsar Timing shape=(5, 6)
Pulsation Timing Variations shape=(1, 6)
Radial Velocity shape=(553, 6)
Transit shape=(397, 6)
Transit Timing Variations shape=(4, 6)
