In [1]:
import numpy as np 

In [2]:
# making a n-dimensional array
a = np.array([1, 2, 3, 4, 5, 6])
a.ndim

1

In [3]:
# Indexing an array, index start from 0
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a.shape, a.ndim, a

((3, 3),
 2,
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [4]:
np.array([np.arange(4)])

array([[0, 1, 2, 3]])

In [5]:
d3 = np.array([
    [
        [np.random.randint(0, 244, 3)]
    ],
    [
        [20.9, 129, 244],
        [211, 78, 157]
    ],
])

d3.shape

(2,)

In [6]:
# generating random data
data = np.random.randn(2, 3)
data

array([[-0.20775151, -0.58759501,  0.34151083],
       [ 0.43808527, -0.27153506,  0.29868268]])

In [7]:
#mathematical operation on the data (multiplication)
data * 10

array([[-2.07751511, -5.87595012,  3.41510829],
       [ 4.38085267, -2.71535059,  2.98682676]])

In [8]:
# addition operation
data + data

array([[-0.41550302, -1.17519002,  0.68302166],
       [ 0.87617053, -0.54307012,  0.59736535]])

In [9]:
# shape of the array
data.shape

(2, 3)

In [10]:
# data's data type
data.dtype

dtype('float64')

# Creating ndarrays

In [11]:
# using a object sequence
data1 = [6, 7.5, 8, 9, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 9. , 1. ])

In [12]:
# ndimensional arrays with a list object of lists
data2 = [[1,2,3,4], [5, 6, 7, 8]]
arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
# checking the number of dimensions using 'ndim'
arr2.ndim

2

In [14]:
# the shape of the array, 'shape'
arr2.shape

(2, 4)

In [15]:
# data types with 'dtype'
arr1.dtype

dtype('float64')

In [16]:
arr2.dtype

dtype('int64')

In [17]:
# array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# array of zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
# an empty array , may return an array of 'garbage values'
np.empty((2, 3, 2))

array([[[4.64795696e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [21]:
# range function, with 'arange'
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.ones_like((1, 2))

array([1, 1])

In [23]:
np.asarray(data)

array([[-0.20775151, -0.58759501,  0.34151083],
       [ 0.43808527, -0.27153506,  0.29868268]])

In [24]:
# create an array of any shape and fill with a constant value
np.full(3, fill_value=10) # column array of values 10,
np.full((5, 8), fill_value=12) # multi-dimensional array with values 12

array([[12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12]])

## Data Types for ndarrays

In [25]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr2 = np.array([1, 3, 4], dtype=np.int32)

arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int32'))

In [26]:
# use 'astype' to change an array's data type
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr.dtype

dtype('int64')

In [27]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [28]:
arr = np.array([-1.2, 3.7, 9.8, -0.1, 10.1, 0.5 ], dtype=np.float32)
arr 

array([-1.2,  3.7,  9.8, -0.1, 10.1,  0.5], dtype=float32)

In [29]:
arr.astype(np.int32)

array([-1,  3,  9,  0, 10,  0], dtype=int32)

## Arithmetic, Slicing and Indexing

In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
arr

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [31]:
# multiplication
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

In [32]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [33]:
# division by scalar element
1 / arr

array([[1.        , 0.5       , 0.33333334],
       [0.25      , 0.2       , 0.16666667]], dtype=float32)

In [34]:
# array raised to the power of x
arr ** 0.5

array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898]], dtype=float32)

In [35]:
# array comparison yields bool
arr2 = np.array([[0, 4, 1], [7, 2, 12]], dtype=np.float32)
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]], dtype=float32)

In [36]:
# this compares the elements of an array with it's corresponding elements of another array
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [37]:
# Basic indexing and slicing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# selecting the N-th element
arr[5]

5

In [39]:
arr[5:8]

array([5, 6, 7])

In [40]:
# can assign new values to a slice
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [41]:
# this is not a copy of the original array
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [42]:
# assigning a values to any index would affect the original array
arr_slice [1] = 12345

In [43]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [44]:
# assigns 64 to every element in the array
arr_slice[:] = 64

arr_slice

array([64, 64, 64])

In [45]:
# to make a copy of an array use the 'copy()' function
arr_copy = arr[5:8].copy()
arr_copy

# change the value of an element and if the original array changes
arr_copy[2] = 6
arr_copy, arr

(array([64, 64,  6]), array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9]))

In [46]:
# for multi-dimensional arrays
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float32)
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [47]:
# getting the third row
arr2d[2]

array([7., 8., 9.], dtype=float32)

In [48]:
print(arr2d[2, 2]) # The same as arr2d[0][2], prints 9
print(arr2d[1, 2]) # print 6
print(arr2d[0, 0]) # prints 1
print(arr2d[0, 2]) # print 3

9.0
6.0
1.0
3.0


In [49]:
# prints all the elements of the array arr2d

for row in range(len(arr2d)):
    print(arr2d[row])  

[1. 2. 3.]
[4. 5. 6.]
[7. 8. 9.]


In [50]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d # a 2x2x3 array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
arr3d[0] # first element of the array

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
old_values = arr3d[0].copy() # make a copy of the array
arr3d[0] = 42 # change all the values of the first index to 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
arr3d[1, 0]

array([7, 8, 9])

In [55]:
arr3d[1, 0, 2] # prints 9

9

In [56]:
# looping through a higher Ndarray
for row in range(len(arr3d)):
    print(arr3d[row])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [57]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [58]:
x[0]

array([7, 8, 9])

In [59]:
x[1, 1] # prints 11

11

In [60]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [61]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [62]:
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [63]:
arr2d[:2]

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [64]:
arr2d[:2, 1:]

array([[2., 3.],
       [5., 6.]], dtype=float32)

In [65]:
arr2d[1, :2]

array([4., 5.], dtype=float32)

In [66]:
arr2d[2, 1:]

array([8., 9.], dtype=float32)

In [67]:
arr2d[:2, 2]

array([3., 6.], dtype=float32)

In [68]:
arr2d[:, :1]

array([[1.],
       [4.],
       [7.]], dtype=float32)

In [69]:
arr2d[:2, 1:] = 0
arr2d

array([[1., 0., 0.],
       [4., 0., 0.],
       [7., 8., 9.]], dtype=float32)

In [70]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [71]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [72]:
data

array([[ 0.66113187,  1.41070654,  0.10696651, -0.95616146],
       [-1.2986837 ,  1.6592885 , -1.03083215,  0.46453633],
       [ 0.51934668,  1.75038783,  1.40733705, -1.16548428],
       [-0.78173482,  1.5469495 , -0.70505305, -0.83738344],
       [-0.92926327, -0.96223994,  0.53283157, -1.33812643],
       [ 0.28589483, -0.58228227, -0.39795794, -2.88202496],
       [ 2.31862695,  0.50426576,  1.57043173,  1.08781574]])

In [73]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [74]:
data[names =='Bob']

array([[ 0.66113187,  1.41070654,  0.10696651, -0.95616146],
       [-0.78173482,  1.5469495 , -0.70505305, -0.83738344]])

In [75]:
data[names=='Bob', 3]

array([-0.95616146, -0.83738344])

In [76]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [77]:
data[names != 'Bob']

array([[-1.2986837 ,  1.6592885 , -1.03083215,  0.46453633],
       [ 0.51934668,  1.75038783,  1.40733705, -1.16548428],
       [-0.92926327, -0.96223994,  0.53283157, -1.33812643],
       [ 0.28589483, -0.58228227, -0.39795794, -2.88202496],
       [ 2.31862695,  0.50426576,  1.57043173,  1.08781574]])

In [78]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [79]:
data[mask]

array([[ 0.66113187,  1.41070654,  0.10696651, -0.95616146],
       [ 0.51934668,  1.75038783,  1.40733705, -1.16548428],
       [-0.78173482,  1.5469495 , -0.70505305, -0.83738344],
       [-0.92926327, -0.96223994,  0.53283157, -1.33812643]])

In [80]:
# setting any valu lesser then 0 t0 0
data[data < 0] = 0
data

array([[0.66113187, 1.41070654, 0.10696651, 0.        ],
       [0.        , 1.6592885 , 0.        , 0.46453633],
       [0.51934668, 1.75038783, 1.40733705, 0.        ],
       [0.        , 1.5469495 , 0.        , 0.        ],
       [0.        , 0.        , 0.53283157, 0.        ],
       [0.28589483, 0.        , 0.        , 0.        ],
       [2.31862695, 0.50426576, 1.57043173, 1.08781574]])

In [81]:
# fancy indexing
arr = np.empty((8,4))

for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [82]:
# selecting an index
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [83]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [84]:
arr[[0, 7, 4, 5, 1], [0, 3, 2, 1, 0]]

array([ 0, 31, 18, 21,  4])

## Transposing Arrays and Swapping Axes

In [85]:
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
# new the transpose method /T attribute to change the shape of the array
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [87]:
arr = np.random.randn(6, 3)
arr

array([[-2.26617452, -0.61733343,  0.1475885 ],
       [ 1.43077239, -1.35919133, -0.02504328],
       [-0.69964609, -0.2256351 ,  0.35454608],
       [ 1.06010927,  0.65911979,  1.00399747],
       [ 0.40237126,  1.11194044,  0.99497726],
       [-0.76508774, -2.07843432, -0.11766752]])

In [88]:
np.dot(arr, arr.T )

array([[ 5.5384299 , -2.40700178,  1.77713915, -2.66111083, -1.4514343 ,
         2.99954296],
       [-2.40700178,  3.89513787, -0.70323202,  0.59576177, -0.96055562,
         1.73327028],
       [ 1.77713915, -0.70323202,  0.66611877, -0.53445849, -0.17964498,
         0.96253982],
       [-2.66111083,  0.59576177, -0.53445849,  2.56628148,  2.15841411,
        -2.2991517 ],
       [-1.4514343 , -0.96055562, -0.17964498,  2.15841411,  2.38829393,
        -2.736021  ],
       [ 2.99954296,  1.73327028,  0.96253982, -2.2991517 , -2.736021  ,
         4.91909411]])

In [89]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [90]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [91]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [92]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal function

In [93]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
# sqrt
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [95]:
# exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [96]:
# binary ufunc
x = np.random.randn(8)
y = np.random.randn(8)

x, y

(array([ 0.50326241, -0.5136361 , -0.11765178, -1.35830356,  0.61254148,
        -1.49293357, -1.06629112,  0.50299463]),
 array([-1.15895113, -0.65821711,  1.12531175,  0.29968499, -0.17966451,
        -0.39614181, -0.34701081, -1.16527947]))

In [97]:
# max value between two ndarrays
np.maximum(x, y)

array([ 0.50326241, -0.5136361 ,  1.12531175,  0.29968499,  0.61254148,
       -0.39614181, -0.34701081,  0.50299463])

In [98]:
arr = np.random.randn(8) * 5
remainder, whole = np.modf(arr)

In [99]:
arr

array([ 1.27462284,  1.8333352 ,  2.86799202,  2.16277929, -9.77029793,
        6.96505981, -9.2968051 , -3.39865365])

In [100]:
whole

array([ 1.,  1.,  2.,  2., -9.,  6., -9., -3.])

In [101]:
remainder

array([ 0.27462284,  0.8333352 ,  0.86799202,  0.16277929, -0.77029793,
        0.96505981, -0.2968051 , -0.39865365])

In [102]:
np.sign(whole)

array([ 1.,  1.,  1.,  1., -1.,  1., -1., -1.])

In [103]:
np.sign(remainder)

array([ 1.,  1.,  1.,  1., -1.,  1., -1., -1.])

In [104]:
arr1 = np.arange(20).reshape(2, 2, 5)
arr1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [105]:
arr2 = np.random.randn(20).reshape(2, 2, 5)
arr2

array([[[ 0.44908584, -0.24217203, -1.32630951,  0.2321901 ,
         -1.17364432],
        [ 0.43718844,  0.13334623,  0.12823856, -0.2813161 ,
         -0.94784619]],

       [[ 0.08441255, -0.65056961,  0.28182073, -0.28503175,
         -0.64606935],
        [-1.61617845, -0.4499832 ,  0.63030586, -0.32324373,
          0.85824491]]])

In [106]:
np.add(arr1, arr2)

array([[[ 0.44908584,  0.75782797,  0.67369049,  3.2321901 ,
          2.82635568],
        [ 5.43718844,  6.13334623,  7.12823856,  7.7186839 ,
          8.05215381]],

       [[10.08441255, 10.34943039, 12.28182073, 12.71496825,
         13.35393065],
        [13.38382155, 15.5500168 , 17.63030586, 17.67675627,
         19.85824491]]])

In [107]:
np.subtract(arr1, arr2)

array([[[-0.44908584,  1.24217203,  3.32630951,  2.7678099 ,
          5.17364432],
        [ 4.56281156,  5.86665377,  6.87176144,  8.2813161 ,
          9.94784619]],

       [[ 9.91558745, 11.65056961, 11.71817927, 13.28503175,
         14.64606935],
        [16.61617845, 16.4499832 , 16.36969414, 18.32324373,
         18.14175509]]])

In [108]:
np.floor_divide(arr1, arr2)

array([[[  0.,  -5.,  -2.,  12.,  -4.],
        [ 11.,  44.,  54., -29., -10.]],

       [[118., -17.,  42., -46., -22.],
        [-10., -36.,  26., -56.,  22.]]])

In [109]:
np.copysign(arr1, arr2)

array([[[  0.,  -1.,  -2.,   3.,  -4.],
        [  5.,   6.,   7.,  -8.,  -9.]],

       [[ 10., -11.,  12., -13., -14.],
        [-15., -16.,  17., -18.,  19.]]])

In [110]:
np.sign(arr1, arr2)

array([[[0., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [111]:
arr1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [112]:
np.cos(arr1)

array([[[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ,
         -0.65364362],
        [ 0.28366219,  0.96017029,  0.75390225, -0.14550003,
         -0.91113026]],

       [[-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,
          0.13673722],
        [-0.75968791, -0.95765948, -0.27516334,  0.66031671,
          0.98870462]]])

In [113]:
np.cosh(arr2)

array([[[1.        , 1.54308063, 1.54308063, 1.54308063, 1.54308063],
        [1.54308063, 1.54308063, 1.54308063, 1.54308063, 1.54308063]],

       [[1.54308063, 1.54308063, 1.54308063, 1.54308063, 1.54308063],
        [1.54308063, 1.54308063, 1.54308063, 1.54308063, 1.54308063]]])

In [114]:
np.logical_not(arr1, arr2)

array([[[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

##  Mathematical and statistical methods

In [115]:
arr = np.random.randn(5, 4)
arr

array([[-0.12177196, -1.08804834, -0.40915359,  0.37555787],
       [ 0.68131199, -0.59737251, -1.01578317, -1.48564222],
       [-0.4764412 ,  0.97397398, -0.33658324,  1.95881887],
       [-0.35050284,  1.22383036, -0.17577088,  1.05969722],
       [ 0.04605716, -0.56081565, -1.35600047,  0.70151469]])

In [116]:
# getting the mean 
arr.mean()

-0.04765619662674657

In [117]:
# also gets the mean 
np.mean(arr)

-0.04765619662674657

In [118]:
np.sum(arr)

-0.9531239325349313

In [119]:
# the axis in which to operate can also be stated 0 = row, 1 = col
arr.mean(axis=0)

array([-0.04426937, -0.00968643, -0.65865827,  0.52198929])

In [120]:
arr.sum(axis=1)

array([-1.24341601, -2.41748591,  2.11976841,  1.75725386, -1.16924428])

In [121]:
# produces the cumulative sum
np.cumsum(arr)

array([-0.12177196, -1.2098203 , -1.61897389, -1.24341601, -0.56210403,
       -1.15947654, -2.1752597 , -3.66090192, -4.13734312, -3.16336915,
       -3.49995239, -1.54113352, -1.89163636, -0.667806  , -0.84357687,
        0.21612035,  0.2621775 , -0.29863815, -1.65463862, -0.95312393])

In [122]:
# produces the cumulative product
np.cumprod(arr)

array([-1.21771961e-01,  1.32493780e-01, -5.42103053e-02, -2.03591070e-02,
       -1.38709037e-02,  8.28609654e-03, -8.41687738e-03,  1.25044684e-02,
       -5.95764392e-03, -5.80259014e-03,  1.95305459e-03,  3.82568019e-03,
       -1.34091177e-03, -1.64104853e-03,  2.88448538e-04,  3.05668113e-04,
        1.40782040e-05, -7.89527710e-06,  1.07059995e-05,  7.51041585e-06])

In [123]:
# using cumsum and cumprod on higher dimensional array

arr = np.arange(0, 9).reshape(3,1, 3)
arr

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [124]:
arr.cumsum(axis=0)

array([[[ 0,  1,  2]],

       [[ 3,  5,  7]],

       [[ 9, 12, 15]]])

In [125]:
arr.cumprod(axis=0)

array([[[ 0,  1,  2]],

       [[ 0,  4, 10]],

       [[ 0, 28, 80]]])

In [126]:
arr.cumprod(axis=1)

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [127]:
arr.std()

2.581988897471611

In [128]:
arr.std(axis=0)

array([[2.44948974, 2.44948974, 2.44948974]])

In [129]:
arr.min()

0

In [130]:
arr.max()

8

In [131]:
arr.argmin()

0

In [132]:
arr.argmax()

8

In [133]:
arr.var()

6.666666666666667

## Methods for boolean arrays, sorting

In [134]:
arr = np.random.randn(100)

(arr > 0).sum() # number of positive values

49

In [138]:
bools = np.array([False, False, False, True, False])
bools.any() # test if a value is positive

True

In [139]:
bools.all() # test if all value are True

False

####  Sorting

In [142]:
# The numpy array can also be sorted like the python list using the `sort()` function

In [144]:
arr = np.random.randn(6)
arr

array([ 0.12072843,  0.60274352,  0.74879582,  2.3408379 , -0.85829073,
       -0.03748226])

In [146]:
arr.sort()
arr

array([-0.85829073, -0.03748226,  0.12072843,  0.60274352,  0.74879582,
        2.3408379 ])

In [150]:
# You can also sort by axis

arr = np.random.randn(5, 3)
arr

array([[ 2.16835478,  1.59643748,  0.40104   ],
       [ 0.69637932,  1.15180848,  0.08112107],
       [ 0.52212322, -0.29181674,  1.07421491],
       [-1.52353173,  0.13331756, -0.25878667],
       [ 0.47949762, -0.23834009,  1.11910836]])

In [149]:
arr1 = arr.copy()

In [167]:
arr.sort()
arr

array([[ 0.40104   ,  1.59643748,  2.16835478],
       [ 0.08112107,  0.69637932,  1.15180848],
       [-0.29181674,  0.52212322,  1.07421491],
       [-1.52353173, -0.25878667,  0.13331756],
       [-0.23834009,  0.47949762,  1.11910836]])

###  unique and other set logic

In [171]:
# The `unique()` function returns the sorted unique values in a array
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [173]:
ints = [3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3]
np.unique(ints)

array([1, 2, 3, 4, 5])

#### File Input and output with arrays 

##### Numpy has the facility for saving and load data in either binary form or text form, numpy files has the `.npy` extension name.
> 
    1. np.save : Saving the file to disk, this takes two argument
        . file name in which the numpy object is to be saved .
        . Numpy object name.
    2. np.load : reading file from the disk, takes only one argument.
        . The file that is to be read.

In [176]:
arr = np.arange(10)

# saving the arr obj
np.save('arr.npy', arr)

In [180]:
# reading the file

arr = np.load('arr.npy')
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
# For multiple objects use the savez function
np.savez('saved files.npz', a=names, b=arr)

In [183]:
loadthis = np.load('saved files.npz')

In [185]:
loadthis['a']

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [186]:
loadthis['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
a = np.random.randint(3, 5, size=(3, 5))
a

array([[3, 4, 4, 3, 3],
       [3, 4, 3, 4, 4],
       [4, 3, 3, 4, 3]])

In [204]:
b = np.random.randint(2, 9, size=(3,5, 5))
b

array([[[3, 8, 2, 6, 3],
        [5, 8, 8, 3, 4],
        [3, 3, 5, 4, 4],
        [6, 8, 4, 5, 6],
        [5, 7, 3, 4, 2]],

       [[5, 7, 4, 8, 3],
        [8, 6, 5, 5, 2],
        [7, 4, 3, 7, 5],
        [3, 8, 2, 4, 3],
        [6, 5, 5, 7, 7]],

       [[6, 7, 4, 7, 6],
        [8, 8, 2, 8, 8],
        [5, 8, 6, 3, 2],
        [7, 3, 7, 2, 2],
        [8, 4, 3, 7, 8]]])

In [205]:
a.dot(b)

array([[[ 74, 113,  79,  73,  65],
        [102, 100,  65, 105,  67],
        [115, 106,  74,  92,  88]],

       [[ 82, 125,  81,  78,  69],
        [104, 109,  69, 109,  72],
        [125, 105,  78,  98,  96]],

       [[ 75, 118,  72,  77,  66],
        [ 95, 105,  63, 105,  66],
        [115, 100,  77,  90,  86]]])

In [220]:
x = np.array([[1, 2, 3],[4, 5, 6]], dtype=float)
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [221]:
y = np.array([[6, 23, 3],[-1, 7, 3],[8, 9, 3]], dtype=np.float32)
y

array([[ 6., 23.,  3.],
       [-1.,  7.,  3.],
       [ 8.,  9.,  3.]], dtype=float32)

In [222]:
x.dot(y)

array([[ 28.,  64.,  18.],
       [ 67., 181.,  45.]])

In [230]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [232]:
# this also performs the dot multiplication 
x @ np.ones((5, 3, 5))

array([[[ 6.,  6.,  6.,  6.,  6.],
        [15., 15., 15., 15., 15.]],

       [[ 6.,  6.,  6.,  6.,  6.],
        [15., 15., 15., 15., 15.]],

       [[ 6.,  6.,  6.,  6.,  6.],
        [15., 15., 15., 15., 15.]],

       [[ 6.,  6.,  6.,  6.,  6.],
        [15., 15., 15., 15., 15.]],

       [[ 6.,  6.,  6.,  6.,  6.],
        [15., 15., 15., 15., 15.]]])

In [251]:
c = np.random.randint(-3,7, size=(6, 6) ) * 5
c

array([[  5,  25,  -5,  30,  20,  25],
       [-15,  -5,  10, -15,  -5,  -5],
       [ 20,  20,  20,  -5,  -5,  15],
       [ 25,  25, -10,  25,   5,   5],
       [  0,  20,   5,   5,  -5,  25],
       [-15,  -5,  20,   5,  10, -10]])

In [252]:
# gettign the elements in the diagonal
diag = []
for i in range(5):
    diag.append(c[i][i])
diag

[5, -5, 20, 25, -5]

In [246]:
diag

[array([ 25,  25,  -5,  25,  15,  10, -15]),
 array([20, 15, 30, 20,  5, 25, 20]),
 array([-10, -10,  30,   5,  20,  25,  20]),
 array([  5,  30,  15,   5, -10,  25,  10]),
 array([-10,  20,  -5,   5,  15, -10,   0])]