In [1]:
import numpy as np 

In [2]:
# making a n-dimensional array
a = np.array([1, 2, 3, 4, 5, 6])
a.ndim

1

In [3]:
# Indexing an array, index start from 0
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a.shape, a.ndim, a

((3, 3),
 2,
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [4]:
np.array([np.arange(4)])

array([[0, 1, 2, 3]])

In [5]:
d3 = np.array([
    [
        [np.random.randint(0, 244, 3)]
    ],
    [
        [20.9, 129, 244],
        [211, 78, 157]
    ],
])

d3.shape

(2,)

In [6]:
# generating random data
data = np.random.randn(2, 3)
data

array([[ 1.1696125 ,  0.71683743, -0.58831592],
       [ 0.7737818 ,  1.39931667,  0.44906302]])

In [7]:
#mathematical operation on the data (multiplication)
data * 10

array([[11.69612499,  7.16837434, -5.88315923],
       [ 7.73781802, 13.99316672,  4.4906302 ]])

In [8]:
# addition operation
data + data

array([[ 2.339225  ,  1.43367487, -1.17663185],
       [ 1.5475636 ,  2.79863334,  0.89812604]])

In [9]:
# shape of the array
data.shape

(2, 3)

In [10]:
# data's data type
data.dtype

dtype('float64')

# Creating ndarrays

In [11]:
# using a object sequence
data1 = [6, 7.5, 8, 9, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 9. , 1. ])

In [12]:
# ndimensional arrays with a list object of lists
data2 = [[1,2,3,4], [5, 6, 7, 8]]
arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
# checking the number of dimensions using 'ndim'
arr2.ndim

2

In [14]:
# the shape of the array, 'shape'
arr2.shape

(2, 4)

In [15]:
# data types with 'dtype'
arr1.dtype

dtype('float64')

In [16]:
arr2.dtype

dtype('int64')

In [17]:
# array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# array of zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
# an empty array , may return an array of 'garbage values'
np.empty((2, 3, 2))

array([[[4.68096912e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [21]:
# range function, with 'arange'
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.ones_like((1, 2))

array([1, 1])

In [23]:
np.asarray(data)

array([[ 1.1696125 ,  0.71683743, -0.58831592],
       [ 0.7737818 ,  1.39931667,  0.44906302]])

In [24]:
# create an array of any shape and fill with a constant value
np.full(3, fill_value=10) # column array of values 10,
np.full((5, 8), fill_value=12) # multi-dimensional array with values 12

array([[12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12]])

## Data Types for ndarrays

In [25]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr2 = np.array([1, 3, 4], dtype=np.int32)

arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int32'))

In [26]:
# use 'astype' to change an array's data type
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr.dtype

dtype('int64')

In [27]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [28]:
arr = np.array([-1.2, 3.7, 9.8, -0.1, 10.1, 0.5 ], dtype=np.float32)
arr 

array([-1.2,  3.7,  9.8, -0.1, 10.1,  0.5], dtype=float32)

In [29]:
arr.astype(np.int32)

array([-1,  3,  9,  0, 10,  0], dtype=int32)

## Arithmetic, Slicing and Indexing

In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
arr

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [31]:
# multiplication
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

In [32]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [33]:
# division by scalar element
1 / arr

array([[1.        , 0.5       , 0.33333334],
       [0.25      , 0.2       , 0.16666667]], dtype=float32)

In [34]:
# array raised to the power of x
arr ** 0.5

array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898]], dtype=float32)

In [35]:
# array comparison yields bool
arr2 = np.array([[0, 4, 1], [7, 2, 12]], dtype=np.float32)
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]], dtype=float32)

In [36]:
# this compares the elements of an array with it's corresponding elements of another array
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [37]:
# Basic indexing and slicing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# selecting the N-th element
arr[5]

5

In [39]:
arr[5:8]

array([5, 6, 7])

In [40]:
# can assign new values to a slice
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [41]:
# this is not a copy of the original array
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [42]:
# assigning a values to any index would affect the original array
arr_slice [1] = 12345

In [43]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [44]:
# assigns 64 to every element in the array
arr_slice[:] = 64

arr_slice

array([64, 64, 64])

In [45]:
# to make a copy of an array use the 'copy()' function
arr_copy = arr[5:8].copy()
arr_copy

# change the value of an element and if the original array changes
arr_copy[2] = 6
arr_copy, arr

(array([64, 64,  6]), array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9]))

In [46]:
# for multi-dimensional arrays
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float32)
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [47]:
# getting the third row
arr2d[2]

array([7., 8., 9.], dtype=float32)

In [48]:
print(arr2d[2, 2]) # The same as arr2d[0][2], prints 9
print(arr2d[1, 2]) # print 6
print(arr2d[0, 0]) # prints 1
print(arr2d[0, 2]) # print 3

9.0
6.0
1.0
3.0


In [49]:
# prints all the elements of the array arr2d

for row in range(len(arr2d)):
    print(arr2d[row])  

[1. 2. 3.]
[4. 5. 6.]
[7. 8. 9.]


In [50]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d # a 2x2x3 array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
arr3d[0] # first element of the array

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
old_values = arr3d[0].copy() # make a copy of the array
arr3d[0] = 42 # change all the values of the first index to 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
arr3d[1, 0]

array([7, 8, 9])

In [55]:
arr3d[1, 0, 2] # prints 9

9

In [56]:
# looping through a higher Ndarray
for row in range(len(arr3d)):
    print(arr3d[row])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [57]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [58]:
x[0]

array([7, 8, 9])

In [59]:
x[1, 1] # prints 11

11

In [60]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [61]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [62]:
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [63]:
arr2d[:2]

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [64]:
arr2d[:2, 1:]

array([[2., 3.],
       [5., 6.]], dtype=float32)

In [65]:
arr2d[1, :2]

array([4., 5.], dtype=float32)

In [66]:
arr2d[2, 1:]

array([8., 9.], dtype=float32)

In [67]:
arr2d[:2, 2]

array([3., 6.], dtype=float32)

In [68]:
arr2d[:, :1]

array([[1.],
       [4.],
       [7.]], dtype=float32)

In [69]:
arr2d[:2, 1:] = 0
arr2d

array([[1., 0., 0.],
       [4., 0., 0.],
       [7., 8., 9.]], dtype=float32)

In [70]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [71]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [72]:
data

array([[ 0.90651765, -0.48828594,  0.68185049,  1.16099949],
       [-0.69057168, -0.03453382, -0.43040662, -1.04568767],
       [-0.81487983,  0.49228555, -1.9393003 , -0.35777756],
       [-0.41456044, -1.10507422, -2.00541552, -1.65553089],
       [ 0.43602802,  2.35358429,  1.90500853,  0.33509642],
       [-0.25347551, -1.0169627 ,  0.29463931,  1.29533051],
       [ 0.14055844, -0.01963746,  0.72489535, -0.53871851]])

In [73]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [74]:
data[names =='Bob']

array([[ 0.90651765, -0.48828594,  0.68185049,  1.16099949],
       [-0.41456044, -1.10507422, -2.00541552, -1.65553089]])

In [75]:
data[names=='Bob', 3]

array([ 1.16099949, -1.65553089])

In [76]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [77]:
data[names != 'Bob']

array([[-0.69057168, -0.03453382, -0.43040662, -1.04568767],
       [-0.81487983,  0.49228555, -1.9393003 , -0.35777756],
       [ 0.43602802,  2.35358429,  1.90500853,  0.33509642],
       [-0.25347551, -1.0169627 ,  0.29463931,  1.29533051],
       [ 0.14055844, -0.01963746,  0.72489535, -0.53871851]])

In [78]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [79]:
data[mask]

array([[ 0.90651765, -0.48828594,  0.68185049,  1.16099949],
       [-0.81487983,  0.49228555, -1.9393003 , -0.35777756],
       [-0.41456044, -1.10507422, -2.00541552, -1.65553089],
       [ 0.43602802,  2.35358429,  1.90500853,  0.33509642]])

In [80]:
# setting any valu lesser then 0 t0 0
data[data < 0] = 0
data

array([[0.90651765, 0.        , 0.68185049, 1.16099949],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.49228555, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.43602802, 2.35358429, 1.90500853, 0.33509642],
       [0.        , 0.        , 0.29463931, 1.29533051],
       [0.14055844, 0.        , 0.72489535, 0.        ]])

In [81]:
# fancy indexing
arr = np.empty((8,4))

for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [82]:
# selecting an index
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [83]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [84]:
arr[[0, 7, 4, 5, 1], [0, 3, 2, 1, 0]]

array([ 0, 31, 18, 21,  4])

## Transposing Arrays and Swapping Axes

In [85]:
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
# new the transpose method /T attribute to change the shape of the array
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [87]:
arr = np.random.randn(6, 3)
arr

array([[ 2.40830838, -0.75075147, -0.17875241],
       [ 0.41509675, -0.22529777,  0.4209358 ],
       [-1.27273262, -0.1084477 ,  0.29321262],
       [ 0.4497589 ,  0.39536658, -1.5948526 ],
       [ 1.0416636 , -0.1148415 , -2.6829202 ],
       [-0.96761828, -0.17660858,  0.17245779]])

In [88]:
np.dot(arr, arr.T )

array([[ 6.39552946,  1.09358032, -3.03612782,  1.07141982,  3.07444303,
        -2.2285613 ],
       [ 1.09358032,  0.40025135, -0.38045046, -0.57371231, -0.67107247,
        -0.28927203],
       [-3.03612782, -0.38045046,  1.71758285, -1.08293032, -2.09997099,
         1.30123894],
       [ 1.07141982, -0.57371231, -1.08293032,  2.90215261,  4.70195523,
        -0.78006481],
       [ 3.07444303, -0.67107247, -2.09997099,  4.70195523,  8.29631242,
        -1.45034122],
       [-2.2285613 , -0.28927203,  1.30123894, -0.78006481, -1.45034122,
         0.99721741]])

In [89]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [90]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [91]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [92]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal function

In [93]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
# sqrt
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [95]:
# exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [96]:
# binary ufunc
x = np.random.randn(8)
y = np.random.randn(8)

x, y

(array([-1.37251891,  1.19465162, -0.2200444 ,  1.43603614,  0.88669159,
        -1.50211619, -0.71649071,  0.23473236]),
 array([-1.46287312,  0.69068246,  1.76877545,  0.72198166,  0.16924166,
         0.40644857, -0.97056309, -0.32676806]))

In [97]:
# max value between two ndarrays
np.maximum(x, y)

array([-1.37251891,  1.19465162,  1.76877545,  1.43603614,  0.88669159,
        0.40644857, -0.71649071,  0.23473236])

In [98]:
arr = np.random.randn(8) * 5
remainder, whole = np.modf(arr)

In [99]:
arr

array([12.76355479, -1.73201205,  4.47408689,  2.46424775,  7.31861484,
        1.64180207, -6.19422352, -5.56469593])

In [100]:
whole

array([12., -1.,  4.,  2.,  7.,  1., -6., -5.])

In [101]:
remainder

array([ 0.76355479, -0.73201205,  0.47408689,  0.46424775,  0.31861484,
        0.64180207, -0.19422352, -0.56469593])

In [102]:
np.sign(whole)

array([ 1., -1.,  1.,  1.,  1.,  1., -1., -1.])

In [103]:
np.sign(remainder)

array([ 1., -1.,  1.,  1.,  1.,  1., -1., -1.])

In [107]:
arr1 = np.arange(20).reshape(2, 2, 5)
arr1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [117]:
arr2 = np.random.randn(20).reshape(2, 2, 5)
arr2

array([[[-0.3490062 , -0.33905142,  1.3601244 , -0.41554467,
         -0.14032144],
        [ 0.64320245,  0.44329535, -0.49304927,  0.7570342 ,
         -1.74760513]],

       [[ 0.06281774, -0.99064165, -0.36916619, -0.99535451,
         -1.59332627],
        [-0.64544939,  0.1553306 ,  1.09597167, -0.51255622,
          0.50605323]]])

In [118]:
np.add(arr1, arr2)

array([[[-0.3490062 ,  0.66094858,  3.3601244 ,  2.58445533,
          3.85967856],
        [ 5.64320245,  6.44329535,  6.50695073,  8.7570342 ,
          7.25239487]],

       [[10.06281774, 10.00935835, 11.63083381, 12.00464549,
         12.40667373],
        [14.35455061, 16.1553306 , 18.09597167, 17.48744378,
         19.50605323]]])

In [119]:
np.subtract(arr1, arr2)

array([[[ 0.3490062 ,  1.33905142,  0.6398756 ,  3.41554467,
          4.14032144],
        [ 4.35679755,  5.55670465,  7.49304927,  7.2429658 ,
         10.74760513]],

       [[ 9.93718226, 11.99064165, 12.36916619, 13.99535451,
         15.59332627],
        [15.64544939, 15.8446694 , 15.90402833, 18.51255622,
         18.49394677]]])

In [120]:
np.floor_divide(arr1, arr2)

array([[[ -0.,  -3.,   1.,  -8., -29.],
        [  7.,  13., -15.,  10.,  -6.]],

       [[159., -12., -33., -14.,  -9.],
        [-24., 103.,  15., -36.,  37.]]])

In [122]:
np.copysign(arr1, arr2)

array([[[ -0.,  -1.,   2.,  -3.,  -4.],
        [  5.,   6.,  -7.,   8.,  -9.]],

       [[ 10., -11., -12., -13., -14.],
        [-15.,  16.,  17., -18.,  19.]]])

In [124]:
np.sign(arr1, arr2)

array([[[0., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [135]:
arr1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [129]:
np.cos(arr1)

array([[[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ,
         -0.65364362],
        [ 0.28366219,  0.96017029,  0.75390225, -0.14550003,
         -0.91113026]],

       [[-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,
          0.13673722],
        [-0.75968791, -0.95765948, -0.27516334,  0.66031671,
          0.98870462]]])

In [130]:
np.cosh(arr2)

array([[[1.54308063, 1.14954891, 1.08784594, 1.53139688, 1.22134008],
        [1.04050261, 1.49748447, 1.29790204, 1.01060382, 1.44460079]],

       [[1.37316442, 1.00000979, 1.37768066, 1.44077044, 1.00936311],
        [1.3027107 , 1.4946905 , 1.0380969 , 1.22604643, 1.52990444]]])

In [143]:
np.logical_not(arr1, arr2)

array([[[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])