In [1]:
import numpy as np 

In [2]:
# making a n-dimensional array
a = np.array([1, 2, 3, 4, 5, 6])
a.ndim

1

In [3]:
# Indexing an array, index start from 0
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a.shape, a.ndim, a

((3, 3),
 2,
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [4]:
np.array([np.arange(4)])

array([[0, 1, 2, 3]])

In [5]:
d3 = np.array([
    [
        [np.random.randint(0, 244, 3)]
    ],
    [
        [20.9, 129, 244],
        [211, 78, 157]
    ],
])

d3.shape

(2,)

In [6]:
# generating random data
data = np.random.randn(2, 3)
data

array([[ 0.19984928,  0.41322368,  1.16824367],
       [-0.29719501,  0.67390219, -1.04247541]])

In [7]:
#mathematical operation on the data (multiplication)
data * 10

array([[  1.99849283,   4.13223684,  11.68243667],
       [ -2.9719501 ,   6.73902189, -10.42475413]])

In [8]:
# addition operation
data + data

array([[ 0.39969857,  0.82644737,  2.33648733],
       [-0.59439002,  1.34780438, -2.08495083]])

In [9]:
# shape of the array
data.shape

(2, 3)

In [10]:
# data's data type
data.dtype

dtype('float64')

# Creating ndarrays

In [11]:
# using a object sequence
data1 = [6, 7.5, 8, 9, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 9. , 1. ])

In [12]:
# ndimensional arrays with a list object of lists
data2 = [[1,2,3,4], [5, 6, 7, 8]]
arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
# checking the number of dimensions using 'ndim'
arr2.ndim

2

In [14]:
# the shape of the array, 'shape'
arr2.shape

(2, 4)

In [15]:
# data types with 'dtype'
arr1.dtype

dtype('float64')

In [16]:
arr2.dtype

dtype('int64')

In [17]:
# array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# array of zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
# an empty array , may return an array of 'garbage values'
np.empty((2, 3, 2))

array([[[4.67308746e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [21]:
# range function, with 'arange'
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.ones_like((1, 2))

array([1, 1])

In [23]:
np.asarray(data)

array([[ 0.19984928,  0.41322368,  1.16824367],
       [-0.29719501,  0.67390219, -1.04247541]])

In [24]:
# create an array of any shape and fill with a constant value
np.full(3, fill_value=10) # column array of values 10,
np.full((5, 8), fill_value=12) # multi-dimensional array with values 12

array([[12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12]])

## Data Types for ndarrays

In [25]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr2 = np.array([1, 3, 4], dtype=np.int32)

arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int32'))

In [26]:
# use 'astype' to change an array's data type
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr.dtype

dtype('int64')

In [27]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [28]:
arr = np.array([-1.2, 3.7, 9.8, -0.1, 10.1, 0.5 ], dtype=np.float32)
arr 

array([-1.2,  3.7,  9.8, -0.1, 10.1,  0.5], dtype=float32)

In [29]:
arr.astype(np.int32)

array([-1,  3,  9,  0, 10,  0], dtype=int32)

## Arithmetic, Slicing and Indexing

In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
arr

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [31]:
# multiplication
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

In [32]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [33]:
# division by scalar element
1 / arr

array([[1.        , 0.5       , 0.33333334],
       [0.25      , 0.2       , 0.16666667]], dtype=float32)

In [34]:
# array raised to the power of x
arr ** 0.5

array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898]], dtype=float32)

In [35]:
# array comparison yields bool
arr2 = np.array([[0, 4, 1], [7, 2, 12]], dtype=np.float32)
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]], dtype=float32)

In [36]:
# this compares the elements of an array with it's corresponding elements of another array
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [37]:
# Basic indexing and slicing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# selecting the N-th element
arr[5]

5

In [39]:
arr[5:8]

array([5, 6, 7])

In [40]:
# can assign new values to a slice
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [41]:
# this is not a copy of the original array
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [42]:
# assigning a values to any index would affect the original array
arr_slice [1] = 12345

In [43]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [44]:
# assigns 64 to every element in the array
arr_slice[:] = 64

arr_slice

array([64, 64, 64])

In [45]:
# to make a copy of an array use the 'copy()' function
arr_copy = arr[5:8].copy()
arr_copy

# change the value of an element and if the original array changes
arr_copy[2] = 6
arr_copy, arr

(array([64, 64,  6]), array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9]))

In [46]:
# for multi-dimensional arrays
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float32)
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [47]:
# getting the third row
arr2d[2]

array([7., 8., 9.], dtype=float32)

In [48]:
print(arr2d[2, 2]) # The same as arr2d[0][2], prints 9
print(arr2d[1, 2]) # print 6
print(arr2d[0, 0]) # prints 1
print(arr2d[0, 2]) # print 3

9.0
6.0
1.0
3.0


In [49]:
# prints all the elements of the array arr2d

for row in range(len(arr2d)):
    print(arr2d[row])  

[1. 2. 3.]
[4. 5. 6.]
[7. 8. 9.]


In [50]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d # a 2x2x3 array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
arr3d[0] # first element of the array

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
old_values = arr3d[0].copy() # make a copy of the array
arr3d[0] = 42 # change all the values of the first index to 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
arr3d[1, 0]

array([7, 8, 9])

In [55]:
arr3d[1, 0, 2] # prints 9

9

In [56]:
# looping through a higher Ndarray
for row in range(len(arr3d)):
    print(arr3d[row])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [57]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [58]:
x[0]

array([7, 8, 9])

In [59]:
x[1, 1] # prints 11

11

In [60]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [61]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [62]:
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [63]:
arr2d[:2]

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [64]:
arr2d[:2, 1:]

array([[2., 3.],
       [5., 6.]], dtype=float32)

In [65]:
arr2d[1, :2]

array([4., 5.], dtype=float32)

In [66]:
arr2d[2, 1:]

array([8., 9.], dtype=float32)

In [67]:
arr2d[:2, 2]

array([3., 6.], dtype=float32)

In [68]:
arr2d[:, :1]

array([[1.],
       [4.],
       [7.]], dtype=float32)

In [69]:
arr2d[:2, 1:] = 0
arr2d

array([[1., 0., 0.],
       [4., 0., 0.],
       [7., 8., 9.]], dtype=float32)

In [70]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [71]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [72]:
data

array([[-0.85693313, -0.07932106,  1.39686312,  0.83811027],
       [ 0.80841035, -0.70881027,  0.02605082,  0.38566984],
       [ 0.06388346,  0.4376616 ,  0.55026974,  1.20897465],
       [ 0.07189557, -0.82932576,  1.15126438,  0.36093654],
       [-0.21759374,  1.07716053, -0.24603276, -1.53870296],
       [ 1.53736371, -2.55995213, -0.24662632,  0.50482501],
       [ 0.21448782,  1.15831894,  0.20677675, -0.69509627]])

In [73]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [74]:
data[names =='Bob']

array([[-0.85693313, -0.07932106,  1.39686312,  0.83811027],
       [ 0.07189557, -0.82932576,  1.15126438,  0.36093654]])

In [75]:
data[names=='Bob', 3]

array([0.83811027, 0.36093654])

In [76]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [77]:
data[names != 'Bob']

array([[ 0.80841035, -0.70881027,  0.02605082,  0.38566984],
       [ 0.06388346,  0.4376616 ,  0.55026974,  1.20897465],
       [-0.21759374,  1.07716053, -0.24603276, -1.53870296],
       [ 1.53736371, -2.55995213, -0.24662632,  0.50482501],
       [ 0.21448782,  1.15831894,  0.20677675, -0.69509627]])

In [78]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [79]:
data[mask]

array([[-0.85693313, -0.07932106,  1.39686312,  0.83811027],
       [ 0.06388346,  0.4376616 ,  0.55026974,  1.20897465],
       [ 0.07189557, -0.82932576,  1.15126438,  0.36093654],
       [-0.21759374,  1.07716053, -0.24603276, -1.53870296]])

In [80]:
# setting any valu lesser then 0 t0 0
data[data < 0] = 0
data

array([[0.        , 0.        , 1.39686312, 0.83811027],
       [0.80841035, 0.        , 0.02605082, 0.38566984],
       [0.06388346, 0.4376616 , 0.55026974, 1.20897465],
       [0.07189557, 0.        , 1.15126438, 0.36093654],
       [0.        , 1.07716053, 0.        , 0.        ],
       [1.53736371, 0.        , 0.        , 0.50482501],
       [0.21448782, 1.15831894, 0.20677675, 0.        ]])

In [81]:
# fancy indexing
arr = np.empty((8,4))

for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [82]:
# selecting an index
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [83]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [84]:
arr[[0, 7, 4, 5, 1], [0, 3, 2, 1, 0]]

array([ 0, 31, 18, 21,  4])

## Transposing Arrays and Swapping Axes

In [85]:
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
# new the transpose method /T attribute to change the shape of the array
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [87]:
arr = np.random.randn(6, 3)
arr

array([[-1.04184574e+00,  3.20267011e-01,  1.62880825e+00],
       [ 4.70775252e-01, -1.58469056e-03, -3.63840119e-01],
       [-3.18058166e-01, -1.36777880e+00,  3.06299480e-01],
       [-1.23471860e+00, -1.29889594e+00,  7.30612319e-01],
       [-2.43630593e-01, -9.51180632e-02, -5.98785746e-01],
       [ 1.29723517e-01, -1.51853726e-01, -1.60749652e+00]])

In [88]:
np.dot(arr, arr.T )

array([[ 3.84102982, -1.0836085 ,  0.39221624,  2.06042017, -0.75194485,
        -2.80208923],
       [-1.0836085 ,  0.35401148, -0.25901045, -0.84504269,  0.10331776,
         0.64618299],
       [ 0.39221624, -0.25901045,  2.06579922,  2.39310085,  0.02418141,
        -0.32593267],
       [ 2.06042017, -0.84504269,  2.39310085,  3.74545506, -0.01311655,
        -1.13738661],
       [-0.75194485,  0.10331776,  0.02418141, -0.01311655,  0.42694768,
         0.94538542],
       [-2.80208923,  0.64618299, -0.32593267, -1.13738661,  0.94538542,
         2.6239328 ]])

In [89]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [90]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [91]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [92]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal function

In [93]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
# sqrt
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [95]:
# exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [96]:
# binary ufunc
x = np.random.randn(8)
y = np.random.randn(8)

x, y

(array([-0.59041069, -0.05153567,  0.40899842,  0.27217392,  0.63721973,
        -0.12615119,  1.21748092, -1.60665914]),
 array([ 0.56535283, -0.84724529,  1.65375625,  0.1226756 , -0.5147803 ,
         0.41447495,  0.41695433, -0.38883783]))

In [97]:
# max value between two ndarrays
np.maximum(x, y)

array([ 0.56535283, -0.05153567,  1.65375625,  0.27217392,  0.63721973,
        0.41447495,  1.21748092, -0.38883783])

In [98]:
arr = np.random.randn(8) * 5
remainder, whole = np.modf(arr)

In [99]:
arr

array([ 0.92393846,  0.37628217,  5.95050937, -1.57483701, -5.7850398 ,
       -0.48378733,  1.15980496, -2.3664253 ])

In [100]:
whole

array([ 0.,  0.,  5., -1., -5., -0.,  1., -2.])

In [101]:
remainder

array([ 0.92393846,  0.37628217,  0.95050937, -0.57483701, -0.7850398 ,
       -0.48378733,  0.15980496, -0.3664253 ])

In [102]:
np.sign(whole)

array([ 0.,  0.,  1., -1., -1.,  0.,  1., -1.])

In [103]:
np.sign(remainder)

array([ 1.,  1.,  1., -1., -1., -1.,  1., -1.])

In [104]:
arr1 = np.arange(20).reshape(2, 2, 5)
arr1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [105]:
arr2 = np.random.randn(20).reshape(2, 2, 5)
arr2

array([[[ 1.53385803,  1.31764741,  0.19679801, -0.22341087,
         -0.30543713],
        [-0.73015372,  1.23687415,  0.15672226,  0.20032937,
         -0.49234453]],

       [[ 0.45225331,  0.50886812, -0.75882439, -1.0689451 ,
          0.77738475],
        [-1.31987003,  1.13299452, -1.11625678,  0.25930854,
          2.4874575 ]]])

In [106]:
np.add(arr1, arr2)

array([[[ 1.53385803,  2.31764741,  2.19679801,  2.77658913,
          3.69456287],
        [ 4.26984628,  7.23687415,  7.15672226,  8.20032937,
          8.50765547]],

       [[10.45225331, 11.50886812, 11.24117561, 11.9310549 ,
         14.77738475],
        [13.68012997, 17.13299452, 15.88374322, 18.25930854,
         21.4874575 ]]])

In [107]:
np.subtract(arr1, arr2)

array([[[-1.53385803, -0.31764741,  1.80320199,  3.22341087,
          4.30543713],
        [ 5.73015372,  4.76312585,  6.84327774,  7.79967063,
          9.49234453]],

       [[ 9.54774669, 10.49113188, 12.75882439, 14.0689451 ,
         13.22261525],
        [16.31987003, 14.86700548, 18.11625678, 17.74069146,
         16.5125425 ]]])

In [108]:
np.floor_divide(arr1, arr2)

array([[[  0.,   0.,  10., -14., -14.],
        [ -7.,   4.,  44.,  39., -19.]],

       [[ 22.,  21., -16., -13.,  18.],
        [-12.,  14., -16.,  69.,   7.]]])

In [109]:
np.copysign(arr1, arr2)

array([[[  0.,   1.,   2.,  -3.,  -4.],
        [ -5.,   6.,   7.,   8.,  -9.]],

       [[ 10.,  11., -12., -13.,  14.],
        [-15.,  16., -17.,  18.,  19.]]])

In [110]:
np.sign(arr1, arr2)

array([[[0., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [111]:
arr1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [112]:
np.cos(arr1)

array([[[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ,
         -0.65364362],
        [ 0.28366219,  0.96017029,  0.75390225, -0.14550003,
         -0.91113026]],

       [[-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,
          0.13673722],
        [-0.75968791, -0.95765948, -0.27516334,  0.66031671,
          0.98870462]]])

In [113]:
np.cosh(arr2)

array([[[1.        , 1.54308063, 1.54308063, 1.54308063, 1.54308063],
        [1.54308063, 1.54308063, 1.54308063, 1.54308063, 1.54308063]],

       [[1.54308063, 1.54308063, 1.54308063, 1.54308063, 1.54308063],
        [1.54308063, 1.54308063, 1.54308063, 1.54308063, 1.54308063]]])

In [114]:
np.logical_not(arr1, arr2)

array([[[1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

##  Mathematical and statistical methods

In [118]:
arr = np.random.randn(5, 4)
arr

array([[ 1.21352605,  1.08487556,  0.59777166,  0.83981418],
       [-0.46077746, -1.07466056, -1.57159203, -0.85063113],
       [-0.68855912, -1.80481894, -0.57286194, -2.61152736],
       [-0.80987649, -0.06003699, -1.17890239,  1.40629145],
       [ 1.02863084,  0.28325099, -0.66439129,  1.89527405]])

In [119]:
# getting the mean 
arr.mean()

-0.19996004644079907

In [120]:
# also gets the mean 
np.mean(arr)

-0.19996004644079907

In [121]:
np.sum(arr)

-3.999200928815981

In [122]:
# the axis in which to operate can also be stated 0 = row, 1 = col
arr.mean(axis=0)

array([ 0.05658876, -0.31427799, -0.6779952 ,  0.13584424])

In [123]:
arr.sum(axis=1)

array([ 3.73598744, -3.95766119, -5.67776736, -0.64252442,  2.54276459])

In [125]:
# produces the cumulative sum
np.cumsum(arr)

array([ 1.21352605,  2.2984016 ,  2.89617326,  3.73598744,  3.27520998,
        2.20054942,  0.62895739, -0.22167375, -0.91023287, -2.7150518 ,
       -3.28791374, -5.8994411 , -6.7093176 , -6.76935458, -7.94825697,
       -6.54196552, -5.51333468, -5.23008369, -5.89447498, -3.99920093])

In [126]:
# produces the cumulative product
np.cumprod(arr)

array([ 1.21352605,  1.31652475,  0.78698118,  0.66091796, -0.3045361 ,
        0.32727293, -0.51433954,  0.43751322, -0.30125372,  0.54370842,
       -0.31146986,  0.81341205, -0.6587633 ,  0.03955016, -0.04662578,
       -0.06556944, -0.06744675, -0.01910436,  0.01269277,  0.02405628])

In [143]:
# using cumsum and cumprod on higher dimensional array

arr = np.arange(0, 9).reshape(3,1, 3)
arr

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [147]:
arr.cumsum(axis=0)

array([[[ 0,  1,  2]],

       [[ 3,  5,  7]],

       [[ 9, 12, 15]]])

In [149]:
arr.cumprod(axis=0)

array([[[ 0,  1,  2]],

       [[ 0,  4, 10]],

       [[ 0, 28, 80]]])

In [150]:
arr.cumprod(axis=1)

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [156]:
arr.std()

2.581988897471611

In [157]:
arr.std(axis=0)

array([[2.44948974, 2.44948974, 2.44948974]])

In [162]:
arr.min()

0

In [163]:
arr.max()

8

In [164]:
arr.argmin()

0

In [165]:
arr.argmax()

8

In [166]:
arr.var()

6.666666666666667