In [1]:
import numpy as np 

In [24]:
# making a n-dimensional array
a = np.array([1, 2, 3, 4, 5, 6])

In [60]:
# Indexing an array, index start from 0
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
# generating random data
data = np.random.randn(2, 3)
data

array([[ 0.24196227, -1.91328024, -1.72491783],
       [-0.56228753, -1.01283112,  0.31424733]])

In [54]:
#mathematical operation on the data (multiplication)
data * 10

array([[  2.41962272, -19.13280245, -17.24917833],
       [ -5.62287529, -10.1283112 ,   3.14247333]])

In [55]:
# addition operation
data + data

array([[ 0.48392454, -3.82656049, -3.44983567],
       [-1.12457506, -2.02566224,  0.62849467]])

In [61]:
# shape of the array
data.shape

(2, 3)

In [63]:
# data's data type
data.dtype

dtype('float64')

# Creating ndarrays

In [66]:
# using a object sequence
data1 = [6, 7.5, 8, 9, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 9. , 1. ])

In [68]:
# ndimensional arrays with a list object of lists
data2 = [[1,2,3,4], [5, 6, 7, 8]]
arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
# checking the number of dimensions using 'ndim'
arr2.ndim

2

In [71]:
# the shape of the array, 'shape'
arr2.shape

(2, 4)

In [72]:
# data types with 'dtype'
arr1.dtype

dtype('float64')

In [73]:
arr2.dtype

dtype('int64')

In [75]:
# array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [81]:
# array of zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [82]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [94]:
# an empty array , may return an array of 'garbage values'
np.empty((2, 3, 2))

array([[[4.66232623e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [95]:
# range function, with 'arange'
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [100]:
np.ones_like((1, 2))

array([1, 1])

In [107]:
np.asarray(data)

array([[ 0.24196227, -1.91328024, -1.72491783],
       [-0.56228753, -1.01283112,  0.31424733]])

In [121]:
# create an array of any shape and fill with a constant value
np.full(3, fill_value=10) # column array of values 10,
np.full((5, 8), fill_value=12) # multi-dimensional array with values 12

array([[12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12]])

## Data Types for ndarrays

In [125]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr2 = np.array([1, 3, 4], dtype=np.int32)

arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int32'))

In [126]:
# use 'astype' to change an array's data type
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr.dtype

dtype('int64')

In [130]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [133]:
arr = np.array([-1.2, 3.7, 9.8, -0.1, 10.1, 0.5 ], dtype=np.float32)
arr 

array([-1.2,  3.7,  9.8, -0.1, 10.1,  0.5], dtype=float32)

In [134]:
arr.astype(np.int32)

array([-1,  3,  9,  0, 10,  0], dtype=int32)